import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const cssPath = path.join(rootDir, 'src/generated/viewer360.min.css');
const outputPath = path.join(rootDir, 'src/generated/injectStyles.ts');

const css = await readFile(cssPath, 'utf8');
const escapedCss = css.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const source = `// This file is auto-generated by scripts/embed-styles.mjs — do not edit manually.

const VIEWER_360_STYLE_ID = 'mmmmzxe-react-360-viewer-styles';

const viewer360Styles = \`${escapedCss}\`;

export function injectViewer360Styles(): void {
    if (typeof document === 'undefined') return;
    if (document.getElementById(VIEWER_360_STYLE_ID)) return;

    const style = document.createElement('style');
    style.id = VIEWER_360_STYLE_ID;
    style.textContent = viewer360Styles;
    document.head.appendChild(style);
}

injectViewer360Styles();
`;

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, source, 'utf8');
